"""empty message

Revision ID: 95dbd36880c8
Revises: 22f71d4ff357
Create Date: 2021-05-20 15:05:07.389818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dbd36880c8'
down_revision = '22f71d4ff357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_clipId_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_userId_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'likes', 'clips', ['clipId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_userId_fkey', 'likes', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('likes_clipId_fkey', 'likes', 'clips', ['clipId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
