"""empty message

Revision ID: 22f71d4ff357
Revises: 436b51f9abc7
Create Date: 2021-05-20 15:00:55.253043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f71d4ff357'
down_revision = '436b51f9abc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clips_userId_fkey', 'clips', type_='foreignkey')
    op.create_foreign_key(None, 'clips', 'users', ['userId'], ['id'])
    op.drop_constraint('comments_clipId_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_userId_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'clips', ['clipId'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_userId_fkey', 'comments', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comments_clipId_fkey', 'comments', 'clips', ['clipId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.create_foreign_key('clips_userId_fkey', 'clips', 'users', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
