"""empty message

Revision ID: eb4492a8000b
Revises: f6822335726c
Create Date: 2021-05-20 14:45:57.662486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4492a8000b'
down_revision = 'f6822335726c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'clipId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'clipId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
