"""empty message

Revision ID: 7472310448eb
Revises: 3d471807e3ea
Create Date: 2021-05-09 23:05:29.042371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7472310448eb'
down_revision = '3d471807e3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('createdAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'createdAt')
    # ### end Alembic commands ###
