"""empty message

Revision ID: 1a59cd32c055
Revises: 1b0ed9b16ea0
Create Date: 2021-05-04 16:09:54.700374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a59cd32c055'
down_revision = '1b0ed9b16ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.drop_column('comments', 'created_at')
    op.add_column('likes', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.drop_column('likes', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('likes', 'createdAt')
    op.add_column('comments', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'createdAt')
    # ### end Alembic commands ###
