"""empty message

Revision ID: 3573b4a482dc
Revises: 8f41b3329caf
Create Date: 2021-05-20 15:25:31.184470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3573b4a482dc'
down_revision = '8f41b3329caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('clipId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clips', 'clips', ['clipId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.drop_column('clips', 'clipId')
    # ### end Alembic commands ###
