"""empty message

Revision ID: 9a31e71be79d
Revises: 7472310448eb
Create Date: 2021-05-10 14:24:34.873687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a31e71be79d'
down_revision = '7472310448eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('userName', sa.String(), nullable=False))
    op.drop_column('comments', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'userName')
    # ### end Alembic commands ###
