"""empty message

Revision ID: f6822335726c
Revises: 9a31e71be79d
Create Date: 2021-05-20 14:42:47.451921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6822335726c'
down_revision = '9a31e71be79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'clipId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'clipId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
